config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  # User routes
  resources :users, only: [:show] do
    collection do
      get 'map'
      get 'locations'
    end
  end

  # Post routes
  resources :posts, only: [:index, :create, :new, :destroy]
  resources :posts do
    resources :likes, only: [:create, :new, :destroy]
    resources :comments, only: [:create, :new]
    post 'join', on: :member
  end

  # Match routes
  resources :matches do
    member do
      patch :accept
      patch :reject
      delete :cancel # this line is to handle match cancellation
    end
  end

  # Chat routes
  get "friends", to: "pages#friends"
  get "chats", to: "pages#chats"
  resources :matches, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to posts_path do %>
      <i class="fa-solid fa-house"></i>
    <% end %>

    <%= link_to chats_path do %>
      <i class="fa-solid fa-comment-dots"></i>
    <% end %>

    <%= link_to new_post_path, class: 'highlight-icon' do %>
      <i class="fa-solid fa-circle-plus" id="post-icon"></i>
    <% end %>

    <%= link_to map_users_path do %>
      <i class="fa-solid fa-location-dot"></i>
    <% end %>
    <!--
    <%= link_to friends_path do %>
      <i class="fa-solid fa-user"></i>
    <% end %>
    -->

    <% if current_user %>
      <%= link_to user_path(current_user) do %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu"%>
        <% else %>
          <%= image_tag "https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", class: "avatar", alt: "dropdown menu" %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
        <%= image_tag "https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", class: "avatar", alt: "dropdown menu" %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-content">
    <div id="title-text-container" class="mx-auto">
      <h1 class="title-text mb-0">
          <strong>Sláinte</strong>
      </h1>
    </div>

    <div class="header-link">
      <%= link_to matches_path do %>
        <i class="bell fa-solid fa-bell fa-xl me-2" style="color: #ffb400; position: relative;">
          <% if user_signed_in? %>
            <% pending_matches_count = current_user.received_matches.where(status: :pending).count %>
            <% if pending_matches_count > 0 %>
              <span class="badge"><%= pending_matches_count %></span>
            <% end %>
          <% end %>
        </i>
      <% end %>
    </div>
  </div>
</nav>