config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  # User routes
  resources :users, only: [:show] do
    collection do
      get 'map'
      get 'locations'
    end
  end

  # Post routes
  resources :posts, only: [:index, :create, :new, :destroy]
  resources :posts do
    resources :likes, only: [:create, :new, :destroy]
    resources :comments, only: [:create, :new]
    post 'join', on: :member
  end

  # Match routes
  resources :matches do
    member do
      patch :accept
      patch :reject
      delete :cancel # this line is to handle match cancellation
    end
  end

  # Chat routes
  get "friends", to: "pages#friends"
  get "chats", to: "pages#chats"
  resources :matches, only: :show do
    resources :messages, only: :create
  end
end

app/views/pages/chats.html.erb
<div class="chat-container">
  <h1 id="chat-header">Your chats!</h1>

  <% if @friends.size > 0 %>
    <ul>
      <% @friends.each do |match| %>
        <% if match.messages.size > 0 %>
          <li>
            <%= link_to "#{match.user == current_user ? match.matched_user.username : match.user.username}", match_path(match) %>
            <% if match.messages.last.user == current_user %>
              <p>You: <%= match.messages.last.content %></p>
            <% else %>
              <p><%= match.messages.last.user.username %>: <%= match.messages.last.content %></p>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to "#{match.user == current_user ? match.matched_user.username : match.user.username}", match_path(match) %>
            <p>No messages yet</p>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p>Currently you don't have any chats</p>
  <% end %>
</div>

app/views/pages/friends.html.erb
<h1>My Friends</h1>

<ul>
  <% @friends.each do |match| %>
    <li>
      <%= link_to match.matched_user.username, match_path(match) %>
    </li>
  <% end %>
</ul>