config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  # User routes
  resources :users, only: [:show] do
    collection do
      get 'map'
      get 'locations'
    end
  end

  # Post routes
  resources :posts, only: [:index, :create, :new, :destroy]
  resources :posts do
    resources :likes, only: [:create, :new, :destroy]
    resources :comments, only: [:create, :new]
    post 'join', on: :member
  end

  # Match routes
  resources :matches do
    member do
      patch :accept
      patch :reject
      delete :cancel # this line is to handle match cancellation
    end
  end

  # Chat routes
  get "friends", to: "pages#friends"
  get "chats", to: "pages#chats"
  resources :matches, only: :show do
    resources :messages, only: :create
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :matched_user, class_name: 'User'
  has_many :messages
  enum :status, [:pending, :accepted, :rejected ], default: :pending
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def create
    @matched_user = User.find(params[:matched_user_id])
    @match = Match.new(matched_user: @matched_user, user: current_user, status: :pending)
    @match.user = current_user

    if @match.save
      flash[:notice] = "Match request sent."
      redirect_to posts_path
    else
      flash[:alert] = @match.errors.full_messages.join(", ")
      redirect_to posts_path
    end
  end

  def update
    @match = current_user.received_matches.find(params[:id])

    if @match.update(match_params)
      flash[:notice] = "Match was accepted by #{@matched_user}"
    else
      flash[:notice] = "Match was rejected by #{@matched_user}"
    end
  end

  def index
    @sent_matches = current_user.sent_matches.where(status: :pending)
    @received_matches = current_user.received_matches.where(status: :pending)
    @accepted_matches = current_user.received_matches.where(status: :accepted)

  end

  def accept
    @match = current_user.received_matches.find(params[:id])
    if @match.update(status: :accepted)
      flash[:notice] = "Match accepted!"
    else
      flash[:alert] = "Failed to accept the match."
    end
    redirect_to matches_path
  end

  def reject
    @match = current_user.received_matches.find(params[:id])
    if @match.update(status: :rejected)
      flash[:notice] = "Match rejected!"
    else
      flash[:alert] = "Failed to reject the match."
    end
    redirect_to matches_path
  end

  def cancel
    @match = current_user.sent_matches.find(params[:id])
    if @match.destroy
      flash[:notice] = "Match request canceled."
    else
      flash[:alert] = "Failed to cancel the match request."
    end
    redirect_to matches_path
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new
  end

  private

  def match_params
    params.require(:match).permit(:status)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_match
    @match = @user.matches.find(params[:id])
  end
end

app/views/matches/index.html.erb
<!-- HTML Content -->
<div class="match-requests-sent-container">
  <h2 class="title-for-requests">Sent</h2>
  <% @sent_matches.each do |match| %>
    <div class="match-request-item">
      <div class="match-request-avatar">
        <div class="match-request-initials">
          <%= match.matched_user.username.split(' ').map { |name| name[0] }.join.upcase %>
        </div>
      </div>
      <div class="match-request-details">
        <div class="match-request-info">
          <strong class="match-username-text"><%= match.matched_user.username %></strong>
          <span>Match request pending...</span>
        </div>
        <div class="match-request-actions">
          <%= button_to 'Cancel Request', cancel_match_path(match), method: :delete, class: "match-request-button" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="match-requests-received-container">
<h2 class="title-for-requests">Received</h2>
  <% @received_matches.each do |match| %>
    <div class="match-request-item">
      <div class="match-request-avatar">
        <div class="match-request-initials">
          <%= match.user.username.split(' ').map { |name| name[0] }.join.upcase %>
        </div>
      </div>
      <div class="match-request-details">
        <div class="match-request-info">
          <strong class="match-username-text"><%= match.user.username %></strong>
          <span>Sent you a match request</span>
        </div>
        <div class="match-request-actions">
          <%= button_to 'Accept', accept_match_path(match), method: :patch, class: "button-accept" %>
          <%= button_to 'Reject', reject_match_path(match), method: :patch, class: "button-reject" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/matches/show.html.erb
<div class="container chat">
  <h1>Chat</h1>

  <div class="messages">
    <% @match.messages.each do |message| %>
      <div class="message <%= message.user == current_user ? 'sent' : 'received' %>">
        <small>
          <strong><%= message.user.username %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>

<div id="simple-form">

  <!-- Wrap input and button in a div for styling -->
  <div class="input-box-wrapper">
    <%= simple_form_for [@match, @message], html: { class: "chat-input" } do |f| %>
      <%= f.input :content, label: false, placeholder: "Start typing to chat", input_html: { class: "chat-textbox-input" } %>
      <%= f.submit "Send", class: "send-btn" %>
    <% end %>
  </div>
</div>
</div>
</div>