config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  # User routes
  resources :users, only: [:show] do
    collection do
      get 'map'
      get 'locations'
    end
  end

  # Post routes
  resources :posts, only: [:index, :create, :new, :destroy]
  resources :posts do
    resources :likes, only: [:create, :new, :destroy]
    resources :comments, only: [:create, :new]
    post 'join', on: :member
  end

  # Match routes
  resources :matches do
    member do
      patch :accept
      patch :reject
      delete :cancel # this line is to handle match cancellation
    end
  end

  # Chat routes
  get "friends", to: "pages#friends"
  get "chats", to: "pages#chats"
  resources :matches, only: :show do
    resources :messages, only: :create
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :photo
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.order(created_at: :desc).includes(:user, :likes)
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.latitude = 51.5318
    @post.longitude = -0.0767
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :photo)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_post.html.erb
<div class="post">

  <div class="post-header">
    <% if user_signed_in? %>
      <%= link_to user_path(post.user) do %>
        <% if post.user.photo.attached? %>
          <%= cl_image_tag post.user.photo.key, class: "avatar ms-2", alt: "User's avatar" %>
        <% else %>
          <%= image_tag "https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", class: "avatar ms-2", alt: "Default avatar" %>
        <% end %>
      <% end %>
    <% end %>
    <p id="post-title"><%= post.content %></p>
  </div>

  <% if post.photo.attached? %>
    <%= link_to post, class: "w-100" do %>
      <%= cl_image_tag post.photo.key, alt: "Post image", class: "post-image" %>
    <% end %>
  <% end %>

  <% pre_like = post.likes.find { |like| like.user_id == current_user.id } %>
  <div class="post-interactions" style="display: flex; align-items: center; justify-content: space-between;">
    <div>
      <div class="like-section" style="text-align: center;">
        <% if pre_like %>
          <%= button_to post_like_path(post, pre_like), method: :delete, remote: true, class: "like-button liked",
            style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
            <i class="fa-solid fa-heart" style="color: #ffb400; font-size: 24px;" id="heart-icon"></i>
          <% end %>
        <% else %>
          <%= button_to post_likes_path(post), method: :post, class: "like-button not-liked",
          style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
            <i class="fa-regular fa-heart" style="color: grey; font-size: 24px;"></i>
          <% end %>
        <% end %>
      </div>

      <p style="margin: 5px 0 0; font-size: 12px; color: #333;">
        <%= post.likes.count %>
      </p>
    </div>

    <% if post.user == current_user %>
      <p class="button-74 mb-0">Your post</p>
    <% else %>
      <% if current_user.sent_matches.where(matched_user: post.user, status: :pending).exists? %>
        <img src="https://res.cloudinary.com/dah2rdyj2/image/upload/fl_preserve_transparency/v1722970847/wait_fxf1fz.jpg?_s=public-apps" alt="Flaticon" class="icon-class" id="icon-hourglass">
      <% elsif current_user.sent_matches.where(matched_user: post.user, status: :accepted).exists? %>
        <img src="https://res.cloudinary.com/dah2rdyj2/image/upload/fl_preserve_transparency/v1722970833/beer_awm9mk.jpg" alt="Flaticon" class="icon-class">
      <% else %>
        <%= button_to 'Join', matches_path(matched_user_id: post.user.id), method: :post, class: "button-74" %>
      <% end %>
    <% end %>

    <%= link_to post, class: "comment-button",
    style: "font-size: 24px; padding: 5px 0; display: inline-flex; align-items: center;" do %>
      <i class="fa-solid fa-comment-dots" style="font-size: 28px"></i>
    <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class="post">

      <div class="post-header">
        <% if user_signed_in? %>
          <%= link_to user_path(post.user) do %>
            <% if post.user.photo.attached? %>
              <%= cl_image_tag post.user.photo.key, class: "avatar ms-2", alt: "User's avatar" %>
            <% else %>
              <%= image_tag "https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg", class: "avatar ms-2", alt: "Default avatar" %>
            <% end %>
          <% end %>
        <% end %>
        <p id="post-title"><%= post.content %></p>
      </div>

      <% if post.photo.attached? %>
        <%= link_to post, class: "w-100" do %>
          <%= cl_image_tag post.photo.key, alt: "Post image", class: "post-image" %>
        <% end %>
      <% end %>

      <% pre_like = post.likes.find { |like| like.user_id == current_user.id } %>
      <div class="post-interactions" style="display: flex; align-items: center; justify-content: space-between;">
        <div>
          <div class="like-section" style="text-align: center;">
            <% if pre_like %>
              <%= button_to post_like_path(post, pre_like), method: :delete, remote: true, class: "like-button liked",
                style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
                <i class="fa-solid fa-heart" style="color: #ffb400; font-size: 24px;" id="heart-icon"></i>
              <% end %>
            <% else %>
              <%= button_to post_likes_path(post), method: :post, class: "like-button not-liked",
              style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
                <i class="fa-regular fa-heart" style="color: grey; font-size: 24px;"></i>
              <% end %>
            <% end %>
          </div>

          <p style="margin: 16px -10px 0; font-size: 12px; color: #333;">
            <%= post.likes.count %>
          </p>
        </div>

        <% if post.user == current_user %>
          <p class="button-74 mb-0">Your post</p>
        <% else %>
          <% if current_user.sent_matches.where(matched_user: post.user, status: :pending).exists? %>
            <img src="https://res.cloudinary.com/dah2rdyj2/image/upload/fl_preserve_transparency/v1722970847/wait_fxf1fz.jpg?_s=public-apps" alt="Flaticon" class="icon-class" id="icon-hourglass">
          <% elsif current_user.sent_matches.where(matched_user: post.user, status: :accepted).exists? %>
            <img src="https://res.cloudinary.com/dah2rdyj2/image/upload/fl_preserve_transparency/v1722970833/beer_awm9mk.jpg" alt="Flaticon" class="icon-class">
          <% else %>
            <%= button_to 'Join', matches_path(matched_user_id: post.user.id), method: :post, class: "button-74" %>
          <% end %>
        <% end %>

        <%= link_to post, class: "comment-button",
        style: "font-size: 24px; padding: 5px 0; display: inline-flex; align-items: center;" do %>
          <i class="fa-solid fa-comment-dots" style="font-size: 28px"></i>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="new-post-background">
  <div class="new-post-container no-asterisk">
    <h1>Create a Post</h1>

    <%= simple_form_for @post, url: posts_path, html: { multipart: true } do |f| %>
      <%= f.input :content, label: "Share Your Sláinte Story!" %>
      <%= f.input :photo, as: :file %>

      <div class="new-post-buttons">
        <%= link_to 'Back', posts_path, class: 'btn btn-custom-yellow' %>
        <%= f.submit 'Create Post!', class: 'btn btn-custom-teal' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-container">
  <%# Post Title %>
  <p id="post-title"><%= @post.content %></p>

  <%# Post Image %>
  <% if @post.photo.attached? %>
    <%= cl_image_tag @post.photo.key, alt: "Post Image", class: "post-image" %>
  <% end %>

  <%# Post Actions - Only show delete/edit options if the current user owns the post %>
  <% if @post.user == current_user %>
    <div class="post-actions">
      <%# Action Buttons %>
      <div class="action-buttons">
        <%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom-yellow" %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-custom-teal" %>
      </div>
    </div>
  <% end %>

  <%# Back Button %>
  <%#= link_to 'Back', posts_path, class: 'btn btn-custom-teal' %>

  <%# Likes Section %>
  <div class="like-section" style="text-align: center;">
    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id } %>
    <% if pre_like %>
      <%= button_to post_like_path(@post, pre_like), method: :delete, class: "like-button liked",
        style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
        <i class="fa-solid fa-heart" style="color: #ffb400; font-size: 24px;" id="heart-icon"></i>
      <% end %>
    <% else %>
      <%= button_to post_likes_path(@post), method: :post, class: "like-button not-liked",
        style: "border: none; background: none; cursor: pointer; display: inline-flex; align-items: center; font-size: 24px;" do %>
        <i class="fa-regular fa-heart" style="color: grey; font-size: 24px;"></i>
      <% end %>
    <% end %>
    <div class="like-count">
      <p>
        <%= @post.likes.count %> <%= @post.likes.count == 1 ? 'Like' : 'Likes' %>
      </p>
    </div>
  </div>

  <%# Comment Section and Form Container %>
  <div class="comments-section-container">
    <%# Comment Form %>
    <div class="comment-form">
      <%= simple_form_for [@post, @comment] do |f| %>
        <div class="comment-input-group">
          <%= f.input :content, label: false, input_html: { class: 'form-control comment-input', placeholder: 'Write your comment' } %>
          <%= f.submit 'Post', class: 'btn btn-custom-teal comment-submit' %>
        </div>
      <% end %>
    </div>

    <%# Display Comments %>
    <ul class="list-unstyled">
      <% if @post.comments.any? %>
        <% @post.comments.each do |comment| %>
          <li class="comment">
            <p><%= comment.content %></p>
            <p><%= comment.user.username %></p>
          </li>
        <% end %>
      <% else %>
        <p>No Comments Yet😔</p>
      <% end %>
    </ul>
  </div>
</div>